name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  BUCKET_NAME: my-website-bucket-234808sfg
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # setup nodejs in runner
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./build

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:      
      # download build output from previous step
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
      - name: check artifacts
        run: ls -l ./build

      # setup, configure aws cli
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: mkdir -p ~/.aws/
      - run: echo "$super_secret" > ~/.aws/credentials
        env: # Or as an environment variable
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: aws configure list-profiles

      # setup and deploy terraform
      - uses: hashicorp/setup-terraform@v2
      - run: terraform -chdir=./infra init -backend-config="password=${{ secrets.GITHUB_TOKEN }}" 
      - run: terraform -chdir=./infra validate
      - run: terraform -chdir=./infra apply -auto-approve -var "bucket_name=$BUCKET_NAME"

      # eigentlicher deployement step
      - run: aws s3 sync --region eu-central-1 ./build s3://$BUCKET_NAME/ --profile techstarter